### ISSUE TITLE
Many pages of the documentation don't load properly

### ISSUE THREAD

**Issue by d4h0** [davedawkins/Sutil#76] opened 2023-03-03 19:01 UTC
Hi,

There seems to be an issue with the documentation. When I go to https://sutil.dev/#documentation-html, for example, the main area stays empty.

There is a lot logged to the console, including the following two errors:

```
TypeError: Cannot read properties of null (reading 'ownerDocument')
Uncaught (in promise) Error: Child not found
```

**Comment by davedawkins** [comment] 2023-03-03 21:07
Oh boy what did I do..I can fix this later tonight

**Comment by davedawkins** [comment] 2023-03-04 01:04
This is fixed with a temporary patch which disables the `Open in REPL` buttons. I need daylight and coffee to fix it properly.

**Comment by davedawkins** [comment] 2023-03-05 11:14
Found root cause, fixed and uploaded

**Closed by davedawkins** 2023-03-05 11:14 UTC

**Comment by d4h0** [comment] 2023-03-05 13:37
Thanks, @davedawkins!
